name: Wheels
on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]   # Linux x86_64; macOS Intel & Apple Silicon
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp* *-musllinux_*"
          # macOS: build for multiple architectures including universal2
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          # macOS baseline
          MACOSX_DEPLOYMENT_TARGET: "11.0"
        run: uvx cibuildwheel --output-dir dist
      - name: Build sdist
        run: python -m pip install build && python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write     # for PyPI Trusted Publishing (OIDC)
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dist, path: dist }
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist
